#login
POST http://127.0.0.1:8080/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"yyx1232",
    "password":"123456"
}
###

#register
POST http://localhost:8080/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "username": "yyx1",
  "password": "123456",
  "matchingPassword": "123456",
  "age": 20,
  "email": "yyx1@123.com"
}